### ISSUE TITLE
AASTeX\BibTeX format - add correct journal macros for ApJL and A&ARv

### ISSUE THREAD

**Issue by ehenneken** [adsabs/export_service#105]
Currently, the export service generates the macro `\apj` for ApJL papers. This should be `\apjl` (see e.g. the AASTeX output for 2019ApJ...875L..25M:
```
\bibitem[Martin et al.(2019)]{2019ApJ...875L..25M} Martin, D.~V., Fabrycky, D.~C., \& Montet, B.~T.\ 2019, \apj, 875, L25.
```
In the case of Astronomy & Astrophysics Review (A&ARv), the AASTeX/BibTeX output should contain `\aapr`. Now, for example for 2019A&ARv..27....3M, the export service produces
```
\bibitem[Maiolino, \& Mannucci(2019)]{2019A&ARv..27....3M} Maiolino, R., \& Mannucci, F.\ 2019, Astronomy and Astrophysics Review, 27, 3.
```

**Comment by golnazads** [comment]
edwin [11:59 AM]
This is a link to a LaTeX style file that has a pretty complete list in it: http://doc.adsabs.harvard.edu/abs_doc/aas_macros.sty

Turns out I am using the same list. The code compares pub field from solr with the name in the list, if found then the macro is returned. However in this list `Astronomy & Astrophysics Review` is listed as `Astronomy & Astrophysics Reviews` and that is why macro is not found. Also `The Astrophysical Journal Letters` is listed as `Astrophysical Journal, Letters` and hence it is not matched. Need to understand why the journal names are listed in this way, what is the matching rule to have the list match with what is in solr. Or should I just modify the list with the correct journal name as appears in solr. @ehenneken @aaccomazzi

**Comment by aaccomazzi** [comment]
I was going to suggest mapping them to bibstems, which should be a more robust solution, e.g.:
```
'A&ARv': '\\aapr'
```
But, alas, I just remembered that this is not a stored field in solr...
So, yes, updating the list to match the canonical journal names is what we should do.

**Comment by golnazads** [comment]
Regarding bibcode 2019ApJ...875L..25M
Here is what we have in solr
```
        "bibcode":"2019ApJ...875L..25M",
        "pub":"The Astrophysical Journal",
        "pub_raw":"The Astrophysical Journal Letters, Volume 875, Issue 2, article id. L25, <NUMPAGES>9</NUMPAGES> pp. (2019)."}]
```
we are matching `pub` and somehow `Letters` did not make it to `pub` hence the macro is `\apj` instead of `\apjl`

**Comment by golnazads** [comment]
fixed the lookup dict in release  v2.0.40 to have journal names matching what we have in solr. There were 6 that I could not verify and so left untouched
```
    ['IAU Cirulars',r'\iaucirc'],
    ['Astrophysics Letters',r'\aplett'],
    ['Astrophysics Space Physics Research',r'\apspr'],
    ['Geophysics Research Letters',r'\grl'],
    ['Journal of Chemical Physics',r'\jcp'],
    ['Journal of Geophysics Research',r'\jgr'],
```

**Comment by aaccomazzi** [comment]
Thanks.  Just cross-referencing the issue of stored bibstem so that one day we can use that for a more reliable output, since bistems are our real identifiers for publications.
https://github.com/romanchyla/montysolr/issues/123

**Comment by golnazads** [comment]
So here is what we have not the bibstem has made it to solr
```
\bibitem[Martin et al.(2019)]{2019ApJ...875L..25M} Martin, D.~V., Fabrycky, D.~C., \& Montet, B.~T.\ 2019, \apjl, 875, L25
\bibitem[Maiolino, \& Mannucci(2019)]{2019A&ARv..27....3M} Maiolino, R., \& Mannucci, F.\ 2019, \aapr, 27, 3
```
