### ISSUE TITLE
No tex manipulation of string in math mode

### ISSUE THREAD

**Issue by golnazads** [adsabs/export_service#112]
From Alberto:
we should not be doing tex manipulation of strings when in math mode (denoted by the $ characters). ADS classic correctly leaves this untouched: http://adsabs.harvard.edu/cgi-bin/nph-bib_query?bibcode=2016arXiv160807704N&data_type=BIBTEX

**Comment by aaccomazzi** [comment]
This is also a good time to review the whole escaping/macro expansion logic in latex/bibtex.  Here is how classic does it (some of it does not apply but some does): /proj/ads/soft/backup/soft.backup.5/server/convert_str.c 
See function `bibtex_str`

**Comment by golnazads** [comment]
Yes, I have seen this code, and actually implemented our own library conversion based on this code before adopting to latexencode.py
Regarding the macro here is the code that grabs the journal name and find the corresponding macro 
https://github.com/adsabs/export_service/blob/master/exportsrv/formatter/bibTexFormat.py#L208
in config. I went through the list @ehenneken point out and adjusted the journal names as appear in solr.
https://github.com/adsabs/export_service/blob/master/config.py#L21
I thought this issue is resolved for now, until bibstem becomes part of solr, and then instead of comparing journal name in this dictionary we compare bibstem.
Is there anything else I should be concern with?

**Comment by aaccomazzi** [comment]
Sorry, instead of "macro" I should have said "entity, markup, and special character" expansion.  Basically handling things such as '\\', '\<sup\>', etc.  Maybe they are all already handled, mentioning it here just in case.  And it looks like classic translates a blackslash into `$\backslash$` while the new ADS uses `\textbackslash`.  I'm not sure which is better, but we ought to at least verify that what we are using now works as expected.

**Comment by golnazads** [comment]
yes, <sup>, <sub>, and the double quotes are explicitly fixed here
https://github.com/adsabs/export_service/blob/master/exportsrv/formatter/toLaTex.py#L9
I can put a math mode around it if you like, here
https://github.com/adsabs/export_service/blob/master/exportsrv/formatter/latexencode.py#L106
if yes, then I shall check for the others one to see if classic also convert those to the math mode.

**Comment by aaccomazzi** [comment]
Googling around suggests that \\textbackslash does not need math mode, while \\backslash does, so no need to change what you have (https://books.google.com/books?id=xgbapN_8aTwC&pg=PA42&lpg=PA42#v=onepage&q&f=false).

However, it looks to me like we need to have a space after the macro, e.g.
```
This \c that -> This \textbackslash c that
```
Otherwise we'd translate it to `This \textbackslashc that` and the latex compilation would fail (unknown macro `\textbackslashc`).  Needs testing.

**Comment by golnazads** [comment]
Here is what is exported now
```
@ARTICLE{2016arXiv160807704N,
       author = {{Nardin}, Denis},
        title = "{Parametrized higher category theory and higher algebra: Expos\textbackslash'e IV -- Stability with respect to an orbital $\infty$-category}",
      journal = {arXiv e-prints},
     keywords = {Mathematics - Algebraic Topology, Mathematics - Algebraic Geometry, Mathematics - Category Theory},
         year = "2016",
        month = "Aug",
          eid = {arXiv:1608.07704},
        pages = {arXiv:1608.07704},
archivePrefix = {arXiv},
       eprint = {1608.07704},
 primaryClass = {math.AT},
       adsurl = {https://dev.adsabs.harvard.edu/abs/2016arXiv160807704N},
      adsnote = {Provided by the SAO/NASA Astrophysics Data System}
}
```
