### ISSUE TITLE
Support bibtex without AASTeX macros

### ISSUE THREAD

**Issue by aaccomazzi** [adsabs/export_service#146]
This needs discussion, but a user has requested bibtex output where the journal field is given as a string at all times rather than as a TeX macro for those journals that have one in the AASTeX package.

This could be a preference users can set in their profile, similar to the bibtex key creation.  Classic used to have a similar option.

Reference: https://v2.hiverhq.com/permalink/bdf13d5a4b85815fd09f5a6dd9a185f3

**Comment by golnazads** [comment]
this is the same as issue 154, right, @aaccomazzi 

Issue 154 -- now closed.

From a user Victoir Veibell veibell@cpi.com | Mon, Jan 13, 2020 at 4:55 PM
Hello,I was wondering if ADS had any sort of BibTeX citation export setting that removed the journal macros (e.g. output "Journal of Geophysical Research" instead of "/jgr"), as some journals don't allow external style files for paper submission.Thank you,Victoir

From Slack, Tuesday, January 14
aaccomazzi 8:09 PM
should this setting apply to all TeX-based formats, such as AASTeX, MNRAS, Icarus, etc?

**Comment by golnazads** [comment]
implemented in v2.0.65.

**Comment by aaccomazzi** [comment]
Correct, can be closed.

**Comment by golnazads** [comment]
Can I keep it open until BBB implements user preference and start using this functionality. Also decision on whether to have one flag for BibTex and one for CSL formats (aastex, aspc, and aasj) or one flag for all formats has to be made on the BBB side. @thostetler

**Comment by golnazads** [comment]
from slack:
After demoing it to @aaccomazzi he suggested we have three options, full journal name, abbreviated journal name, and journal macro. Hence the name is going to change to journalformat and now would have three states: 1=>macro, 2=>full journal name, and 3=>journal name abbreviated.

**Comment by golnazads** [comment]
from slack:
aaccomazzi  11:19 AM
I would add the following section to the application preferences: a pulldown menu with the header
TeX Journal Name Handling
And the options:
Use AASTeX macros (default)
Use Journal Abbreviations
Use Full Journal Name
The help text could say the following:
This setting is used to define how journal names are rendered in the output of the following TeX-based formats: BibTeX, BibTeX ABS, and AASTeX.  If journal macros are used (default), the following file contains the proper journal definitions compatible with most Astronomy Journals: http://adsabs.harvard.edu/abs_doc/aas_macros.html

**Comment by golnazads** [comment]
implemented in v2.0.65.
