### ISSUE TITLE
linefeed in bibtex fields.

### ISSUE THREAD

**Issue by golnazads** [adsabs/export_service#83]
Should there be linefeed to wrap long text in the following fields for bibtex formatting:
author, editor, title, affiliation, journal, booktitle, keywords, and abstract.
@csgrant00 @aaccomazzi @ehenneken

**Comment by golnazads** [comment]
Grant, Carolyn | Thu, Dec 13, 11:22 AM
I replied no in slack, but maybe AA should have the final word.

**Comment by aaccomazzi** [comment]
author: yes
editor: yes
title: no
affiliation: yes (but I don't think we output this, so it should be irrelevant?)
journal: no
booktitle: no
keywords: no
abstract:yes

This based on what I observe in classic, which seems to "work."
When in doubt, please check what classic does on this formatting issue.

**Comment by csgrant00** [comment]
Didn't this all start because someone wanted us not to have linefeeds in
the abstract?

*************************************************************************

 Carolyn Stern Grant              Astrophysics Data System (ADS)

 cgrant@cfa.harvard.edu        Center for Astrophysics

 617-495-7154 (voicemail)      60 Garden Street  MS 83

 617-495-7356 fax                 Cambridge, MA  02138

*************************************************************************

**Comment by aaccomazzi** [comment]
Maybe, but I would like for that person to explain why.  Nothing I know about bibtex suggests that it needs to be that way?

**Comment by golnazads** [comment]
Implemented in v2.0.37.
