### ISSUE TITLE
Custom format bug for arXiv entries

### ISSUE THREAD

**Issue by aaccomazzi** [adsabs/export_service#98]
The following format fails to create the proper output for arXiv papers: `%T|%1.3G|%Y|%q|%V|%p|%d\n`

As an example, when applied to arXiv:1903.00297, this yields

```
From Dark Energy to Exolife: Improving the Digital Information Infrastructure
for Astrophysics|Kurtz M. J. and Accomazzi A.|2019|arXarXiv:1903.00297
```

**Comment by golnazads** [comment]
The issue is because of journal abbreviation for `arXiv`. The pub field in solr is `arXiv e-prints`, q is to get prints out the journal abbreviation and hence call to `get_pub_abbreviation` which returns
[(0.9744898080825806, 'arXiv....'), (0.7244898080825806, 'physics..'), (0.6020408272743225, 'math.....'), (0.5714285969734192, 'astro.ph.'), (0.33673471212387085, 'JBRe.....')] and that messes up what follows.

**Comment by golnazads** [comment]
fixed.

**Comment by golnazads** [comment]
The output is now 
From Dark Energy to Exolife: Improving the Digital Information Infrastructure for Astrophysics|Kurtz, M. J., Accomazzi, A.|2019|arXiv|arXiv:1903.00297
